GET https://doarv2.tk/api/instituicao?token=string

###
configuracao
GET https://doarv2.tk/api/instituicao-id?instituicao_id=int

###
GET https://doarv2.tk/api/info-subdomaim?subdomaim=string

###
POST https://doarv2.tk/api/update-instituicao
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=int
&nome_fantasia=string
&razao_social=string
&email=string
&cnpj=string
&telefone=string

###
POST https://doarv2.tk/api/configuracao-instituicao
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=int
&tags=string
&descricao_site=string
&cor=string
&logo=string

###
POST https://doarv2.tk/api/on_off
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=int

###
POST https://doarv2.tk/api/create-instituicao
Content-Type: application/x-www-form-urlencoded

token=string
&nome_fantasia=string
&sub_domain=string
&razao_social=string
&email=string
&cnpj=string
&telefone=string

###
POST https://doarv2.tk/api/update-domain-person
Content-Type: application/x-www-form-urlencoded

token=string
&instituicao_id=int
&dominio=string



###
GET https://doarv2.tk/api/subdominio-disponivel?subdomain=string
Content-Type: application/x-www-form-urlencoded
// criar ou salvar dados bancario 



